// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD42TAK7yUhK4W4nowo5XhfzBkUd0YnUeM',
    appId: '1:117325103695:web:7072c4914d629dd0ce203a',
    messagingSenderId: '117325103695',
    projectId: 'chat-28caf',
    authDomain: 'chat-28caf.firebaseapp.com',
    storageBucket: 'chat-28caf.appspot.com',
    measurementId: 'G-XYMHXK3SXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mdzDg5ogqelqyaSYpf75MN0Kh_AIIp0',
    appId: '1:117325103695:android:53ff2a98d0c41e1bce203a',
    messagingSenderId: '117325103695',
    projectId: 'chat-28caf',
    storageBucket: 'chat-28caf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfP1dRmxULEutXrdfPIVc3OCBAIljPcDM',
    appId: '1:117325103695:ios:0c5c1d1455aff493ce203a',
    messagingSenderId: '117325103695',
    projectId: 'chat-28caf',
    storageBucket: 'chat-28caf.appspot.com',
    iosBundleId: 'com.example.mtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfP1dRmxULEutXrdfPIVc3OCBAIljPcDM',
    appId: '1:117325103695:ios:0c5c1d1455aff493ce203a',
    messagingSenderId: '117325103695',
    projectId: 'chat-28caf',
    storageBucket: 'chat-28caf.appspot.com',
    iosBundleId: 'com.example.mtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD42TAK7yUhK4W4nowo5XhfzBkUd0YnUeM',
    appId: '1:117325103695:web:9a44d4c2731df6b4ce203a',
    messagingSenderId: '117325103695',
    projectId: 'chat-28caf',
    authDomain: 'chat-28caf.firebaseapp.com',
    storageBucket: 'chat-28caf.appspot.com',
    measurementId: 'G-TNL3V61C5W',
  );
}
